name: Deploy IntellCar to AWS

on:
  push:
    branches: [ "main" ] # Solo disparamos cuando main se actualiza

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Desplegar vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}        # La IP Elástica que nos dio Terraform
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # Tu clave .pem (el contenido)
          script: |
            cd /home/ubuntu/intellcar-project
            git pull origin main
            
            # Reconstruir los contenedores con los cambios nuevos
            docker-compose up -d --build
            
            # Ejecutar las migraciones por si habéis cambiado la BBDD
            docker exec intellcar_api php artisan migrate --force